[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simn"
version = "0.1.0"
description = "SIMN - Shunting-Inhibition Modulated Network"
authors = [
    {name = "sh-owo"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydra-core>=1.3.5",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "omegaconf>=2.3.1",
    "pandas>=2.3.3",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[tool.setuptools.packages.find]
include = ["simn*"] 
